/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/M5tbm1whv0A
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function AddPizza() {
  return (
    (<div
      className="flex flex-col gap-8 p-8 md:p-12 lg:p-16 bg-background text-foreground">
      <div className="grid gap-4">
        <h1 className="text-3xl font-bold">Add New Pizza</h1>
        <p className="text-muted-foreground">Fill out the form below to add a new pizza to your menu.</p>
      </div>
      <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        <div className="grid gap-4">
          <div className="grid gap-1">
            <Label htmlFor="image" className="text-foreground">
              Pizza Image
            </Label>
            <div className="grid gap-2">
              <div
                className="flex h-40 w-full items-center justify-center rounded-lg border-2 border-dashed border-muted transition-colors hover:border-primary">
                <Button variant="ghost" size="icon" className="text-muted-foreground">
                  <UploadIcon className="h-6 w-6" />
                  <span className="sr-only">Upload image</span>
                </Button>
              </div>
              <p className="text-sm text-muted-foreground">Drag and drop or click to upload an image of your pizza.</p>
            </div>
          </div>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="name" className="text-foreground">
              Pizza Name
            </Label>
            <Input
              id="name"
              placeholder="Enter pizza name"
              className="bg-muted text-foreground" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="ingredients" className="text-foreground">
              Ingredients
            </Label>
            <div className="grid gap-2">
              <div className="flex items-center gap-2">
                <Input
                  id="ingredients"
                  placeholder="Add ingredient"
                  className="bg-muted text-foreground" />
                <Button variant="ghost" size="icon" className="text-muted-foreground">
                  <PlusIcon className="h-5 w-5" />
                  <span className="sr-only">Add ingredient</span>
                </Button>
              </div>
              <div className="grid gap-2">
                <div className="flex items-center justify-between rounded-md bg-muted p-2">
                  <div className="text-foreground">Pepperoni</div>
                  <Button variant="ghost" size="icon" className="text-muted-foreground">
                    <XIcon className="h-4 w-4" />
                    <span className="sr-only">Remove ingredient</span>
                  </Button>
                </div>
                <div className="flex items-center justify-between rounded-md bg-muted p-2">
                  <div className="text-foreground">Mushrooms</div>
                  <Button variant="ghost" size="icon" className="text-muted-foreground">
                    <XIcon className="h-4 w-4" />
                    <span className="sr-only">Remove ingredient</span>
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="price" className="text-foreground">
              Price
            </Label>
            <div className="flex items-center gap-2">
              <Input
                id="price"
                type="number"
                placeholder="Enter price"
                className="bg-muted text-foreground" />
              <span className="text-muted-foreground">USD</span>
            </div>
          </div>
          <div className="flex justify-end">
            <Button
              size="lg"
              className="bg-primary text-primary-foreground hover:bg-primary/90">
              Add Pizza
            </Button>
          </div>
        </div>
      </div>
    </div>)
  );
}

function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
